# Generated by Django 3.2 on 2022-04-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppinglist',
            old_name='completed',
            new_name='archived',
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
