# Generated by Django 3.2 on 2022-04-03 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingApp', '0003_auto_20220403_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ShoppingApp.shoppinglistitemcategory'),
        ),
    ]
